version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - funlen
    - err113
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - mnd
    - nlreturn
    - noinlineerr
    - paralleltest
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    gosec:
      excludes:
        - G117
        - G204
        - G304
        - G704
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - gosec
