version: 2

builds:
  - main: .
    binary: claude-notifier
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

brews:
  - name: claude-notifier
    repository:
      owner: felipeelias
      name: homebrew-tap
    homepage: https://github.com/felipeelias/claude-notifier
    description: Notification dispatcher for Claude Code hooks
    license: MIT

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
