name: Bug Report
description: Report a bug in claude-notifier
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows (WSL)
    validations:
      required: true
  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Output of `go version`
      placeholder: "go1.24.0 linux/amd64"
  - type: dropdown
    id: plugin
    attributes:
      label: Plugin
      description: Which notifier plugin is affected?
      options:
        - ntfy
        - terminal-notifier
        - All / not plugin-specific
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Config snippet
      description: Relevant section of your config.toml (redact tokens)
      render: toml
